Repository wp-graphql/wpgraphql-acf, pull requests merged in 2023-12, with the labels that each got.

#16 Build the plugin zip, deploy to WP
  .github/workflows/deploy-to-wordpress.yml
Labels: build scripts

#144 release: v2.0.0 beta.7.0.0
  CHANGELOG.md
  wp-graphql-acf.php
Labels: Release

#143 Create sync-develop-with-main.yml
  .github/workflows/sync-develop-with-main.yml
Labels: Type: Chore

#142 chore: prep for launch on the .org repo
  .env.dist
  .env.testing.dist
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/schema-linter.yml
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.jpg
  .wordpress-org/screenshot-3.jpg
  CHANGELOG.md
  DEVELOPMENT.md
  README.md
  bin/install-test-env.sh
  bin/run-docker.sh
  codeception.dist.yml
  composer.lock
  docker-compose.yml
  docker/Dockerfile.testing
  docker/app.setup.sh
  phpcs.xml.dist
  phpstan.neon.dist
  readme.txt
  src/AcfGraphQLFieldType.php
  src/Admin/OptionsPageRegistration.php
  src/Admin/PostTypeRegistration.php
  src/Admin/Settings.php
  src/Admin/TaxonomyRegistration.php
  src/FieldConfig.php
  src/FieldType/CloneField.php
  src/FieldType/FlexibleContent.php
  src/FieldType/Relationship.php
  src/Registry.php
  src/ThirdParty/AcfExtended/AcfExtended.php
  src/ThirdParty/WPGraphQLContentBlocks/WPGraphQLContentBlocks.php
  src/Utils.php
  src/WPGraphQLAcf.php
  src/assets/admin/js/main.js
  wpgraphql-acf.php
Labels: Documentation, Type: Chore
